/*
===============================================================================
Dimensions Exploration
===============================================================================
Purpose:
    - To explore the structure of dimension tables.

================================================================================

--Data exploration, explore all object in the database
select * from INFORMATION_SCHEMA.TABLES

-- explore all columns in the database
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers'

--dimension exploration identifying the values or categories in each dimension. how data might might be grouped
-- explore all countries
select distinct Country from  gold.Dim_Customers

-- explore all categories major division
select distinct category, Subcategory, Product_name from gold.dim_Product
order by 1,2,3

--Explore dates
--earliest and oldest fid the first and last order
--how many years, months, days of sales
select order_date from gold.fact_sales;
select min(order_date) as first_order_date,max(order_date) as last_order_date,
datediff(year, min(order_date), max(order_date)) as order_range_years,
datediff(MONTH, min(order_date), max(order_date)) as order_range_months,
datediff(DAY, min(order_date), max(order_date)) as order_range_days
from gold.fact_sales;

--find young and the old customers
select
min(birthdate) as old ,
max(birthdate) as new,
DATEDIFF(year, min(birthdate), GETDATE()) as age,
datediff(year, max(birthdate), getdate()) as age2
from gold.Dim_Customers

-- Measure Exploration:-
-- FIND THE TOTAL SALES
select sum(sales_amount)as total_sales from gold.fact_sales
-- FIND HOW MANY ITEMS ARE SOLD
select sum(quantity) as quantity from gold.fact_sales
-- FIND THE AVERAGE PRICE
select avg(price) as avg_price from gold.fact_sales
-- FIND THE TOTAL NUMBERS OF ORDERS
select count(order_number) as total_numbers from gold.fact_sales
select count(distinct order_number) as total_numbers from gold.fact_sales
-- FIND THE TOTAL NUMBERS OF PRODUCTS
select count(product_key) as total_product from gold.dim_Product
select count(distinct product_key) as total_product from gold.dim_Product
-- FIND THE TOTAL NUMBERS OF CUSTOMERS
select count(customer_key) as total_customers from gold.Dim_Customers
-- FIND THE TOTAL NUMBERS OF CUSTOMERS THAT HAS PALCED AN ORDER
select count(customer_key) as total_customers from gold.fact_sales
select count(distinct customer_key) as total_customers from gold.fact_sales

-- GENERATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS :-
select 'TOTAL SALES' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'TOTAL QUANTITY' AS measure_name, sum(quantity) as measure_value from gold.fact_sales
union all
select 'AVERAGE PRICE' as measure_name, avg(price) as measure_value from gold.fact_sales
union all
select 'TOTAL NO OF ORDERS' as measure_name, count(distinct order_number) as measure_value from gold.fact_sales
union all
select 'TOTAL NO OF PRODUCTS' AS mesasure_name, count(distinct product_name) as measure_value from gold.dim_Product
union all
select 'TOTAL NO OF CUSTOMERS', COUNT(customer_key) from gold.Dim_Customers




select 'TOTAL SALES' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'TOTAL QUANTITY', sum(quantity) from gold.fact_sales
union all
select 'AVERAGE PRICE', avg(price) from gold.fact_sales
union all
select 'TOTAL NO OF ORDERS', count(distinct order_number) from gold.fact_sales
union all
select 'TOTAL NO OF PRODUCTS', count(distinct product_name) from gold.dim_Product
union all
select 'TOTAL NO OF CUSTOMERS', COUNT(customer_key) from gold.Dim_Customers


















-- FIND TOTAL CUSTOMERS BY COUNTRIES
select 
country,
count(customer_key) as total_customers
from gold.Dim_Customers
group by Country
order by total_customers desc

-- FIND TOTAL CUSTOMERS BY GENDER
select 
gender,
count(customer_key) as total_customer
from gold.Dim_Customers
group by Gender
order by total_customer desc

-- FIND TOTAL product BY CATEGORY
select
category,
count(product_key) as total_product
from gold.dim_Product
group by category
order by total_product desc

-- WHAT IS THE AVERAGRE COSTS IN EACH CATEGORY
select 
category,
avg(Product_cost) as total_cost
from gold.dim_Product
group by Category
order by total_cost desc

-- WHAT IS THE TOTAL REVENUE GENERATED BY EACH CATEGORY
select 
p.Category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_Product p
on p.Product_key = f.product_key
group by p.Category
order by total_revenue desc

-- FIND TOTAL REVENUE IS GENERATED BY EACH CUSTOMERS
select 
c.Customer_Key,
c.Fitst_name,
c.Last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.Dim_Customers c
on c.Customer_Key =  f.customer_key
group by c.Customer_Key,
		 c.Fitst_name,
		 c.Last_name
order by total_revenue desc

-- WHAT IS THE DISRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
select 
c.Country,
sum(f.quantity) as total_sold_items
from gold.Dim_Customers c
left join gold.fact_sales f
on f.customer_key = c.Customer_Key
group by c.Country
order by total_sold_items desc





--RANKING ANALYSIS--
-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE?
select top 5
p.Product_name,
sum(f.sales_amount) as revenue
from gold.dim_Product p
left join gold.fact_sales f
on p.Product_key = f.product_key
group by p.Product_name
order by revenue desc;;;

select top 5
p.Product_name,
sum(f.sales_amount) total_revenue,
ROW_NUMBER() over (order by sum(f.sales_amount) desc) as row
from gold.fact_sales f
left join gold.dim_Product p
on p.Product_key = f.product_key
group by p.Product_name

-- USING SUB QUERIES :-
select * from (
	select
	p.Product_name,
	sum(f.sales_amount) as total_revenue,
	RANK() over(order by sum(f.sales_amount)desc) as rank
	from gold.fact_sales f
	left join gold.dim_Product p
	on p.Product_key = f.product_key
	group by p.Product_name) as t
where rank <= 5


-- WHAT ARE THE 5 WORST-PERFORMING PRODUCTS IN TERMS OF SALES?
select top 5
p.Product_name,
sum(f.sales_amount) as lowest_revenue
from gold.fact_sales f
left join gold.dim_product p
on f.product_key = p.Product_key
group by p.Product_name
order by lowest_revenue 

-- WHICH 5 SUBCATEGORY GENERATE THE HIGHEST REVENUE?
select top 5
p.Product_name,
sum(f.sales_amount) as subcat
from gold.fact_sales f
left join gold.dim_product p
on p.product_key = f.product_key
group by p.Product_name
order by subcat desc

-- WHICH 5 SUBCATEGORY GENERATE THE HIGHEST REVENUE?
select top 5
p.Product_name,
sum(f.sales_amount) as low_subcat
from gold.fact_sales as f
left join gold.dim_Product as p
on p.Product_key = f.product_key
group by p.Product_name
order by low_subcat 

-- FIND THE TOP 10 COSTUMERS WHO HAVE GENERATED THE HIGHEST REVENUE
select top 10
	c.Customer_id,
	c.Fitst_name,
	c.Last_name,
sum(f.sales_amount) as revenue
from gold.fact_sales as f
left join gold.Dim_Customers as c
on c.Customer_Key = f.customer_key
group by 
	c.Customer_id,
	c.Fitst_name,
	c.Last_name
order by revenue desc

-- THE 3 CUSTOMER WITH THE FEWEST ORDER PLACED
select top 3
c.Customer_id,
c.Fitst_name,
c.Last_name,
count(distinct order_number) as total_order,
RANK () over (order by count(distinct order_number) ) as rank_no
from gold.fact_sales AS f
LEFT JOIN gold.Dim_Customers as c
on c.Customer_Key = f.customer_key
group by
	c.Customer_id,
	c.Fitst_name,
	c.Last_name

